title: Yanni Zhang
logo: ./assets/profile.png
description: I have graduated from Cornell Master's Program in Information Science. I am actively seeking opportunities as Data Analyst.
show_downloads: false
theme: jekyll-theme-minimal
